# Generated by MikroTik Config Tool
# Feature: dhcp
# Generated: 2026-04-09T00:00:00Z

# === IP Pools ===
/ip pool add name="dhcp_pool_lan" ranges="192.168.1.100-192.168.1.200"
/ip pool add name="dhcp_pool_vlan10" ranges="10.10.10.50-10.10.10.150"

# === DHCP Networks ===
/ip dhcp-server network add \
    address="192.168.1.0/24" \
    gateway="192.168.1.1" \
    dns-server="192.168.1.1,8.8.8.8" \
    ntp-server="pool.ntp.org" \
    comment="LAN network"

/ip dhcp-server network add \
    address="10.10.10.0/24" \
    gateway="10.10.10.1" \
    dns-server="10.10.10.1,8.8.8.8" \
    comment="VLAN 10 network"

# === DHCP Servers ===
/ip dhcp-server add \
    name="dhcp-lan" \
    interface="bridge-lan" \
    address-pool="dhcp_pool_lan" \
    lease-time=1d \
    disabled=no

/ip dhcp-server add \
    name="dhcp-vlan10" \
    interface="vlan10" \
    address-pool="dhcp_pool_vlan10" \
    lease-time=12h \
    disabled=no
