# Generated by MikroTik Config Tool
# Feature: firewall
# Generated: 2026-04-09T00:00:00Z

# === INPUT chain — Basic hardening ===
/ip firewall filter

# Allow established/related connections
add chain=input action=accept connection-state=established,related comment="# TOOL:firewall:accept-established"

# Allow ICMP
add chain=input action=accept protocol=icmp comment="# TOOL:firewall:accept-icmp"

# Allow management from LAN
add chain=input action=accept src-address=192.168.1.0/24 in-interface=bridge-lan comment="# TOOL:firewall:accept-lan-mgmt"

# Drop invalid
add chain=input action=drop connection-state=invalid comment="# TOOL:firewall:drop-invalid"

# Drop all other input
add chain=input action=drop comment="# TOOL:firewall:drop-all-input"

# === FORWARD chain ===

# Allow established/related forwarding
add chain=forward action=accept connection-state=established,related comment="# TOOL:firewall:fwd-established"

# Drop invalid forwarding
add chain=forward action=drop connection-state=invalid comment="# TOOL:firewall:fwd-drop-invalid"

# Allow LAN to WAN
add chain=forward action=accept in-interface=bridge-lan out-interface=ether1 comment="# TOOL:firewall:fwd-lan-to-wan"

# === NAT ===
/ip firewall nat

# Masquerade LAN traffic
add chain=srcnat action=masquerade out-interface=ether1 comment="# TOOL:nat:masquerade-wan"

# Port forward: HTTP to internal server
add chain=dstnat action=dst-nat protocol=tcp dst-port=80 to-addresses=192.168.1.100 to-ports=80 comment="# TOOL:nat:dstnat-http"

# Port forward: HTTPS to internal server
add chain=dstnat action=dst-nat protocol=tcp dst-port=443 to-addresses=192.168.1.100 to-ports=443 comment="# TOOL:nat:dstnat-https"
