# Generated by MikroTik Config Tool
# Feature: ospf
# Generated: 2026-04-09T00:00:00Z
# RouterOS v7 syntax

# === OSPF Instance ===
/routing ospf instance
add name="ospf-main" router-id="10.0.0.1" version=2

# === OSPF Area ===
/routing ospf area
add name="backbone" area-id="0.0.0.0" instance="ospf-main"
add name="area1" area-id="0.0.0.1" instance="ospf-main" type=nssa

# === OSPF Interface Templates ===
/routing ospf interface-template
add area="backbone" interfaces="ether2" type=broadcast cost=10 hello-interval=10s dead-interval=40s
add area="backbone" interfaces="ether3" type=point-to-point cost=5 hello-interval=10s dead-interval=40s
add area="area1" interfaces="ether4" type=broadcast cost=20

# === Redistribute connected routes ===
/routing ospf instance set ospf-main redistribute=connected,static
