# Generated by MikroTik Config Tool
# Feature: simple_queues / queue_tree
# Generated: 2026-04-09T00:00:00Z

# === Simple Queues (per-IP bandwidth limit) ===
/queue simple

# Limit a specific client
add name="client-192.168.1.100" target="192.168.1.100/32" \
    max-limit="10M/5M" \
    burst-limit="20M/10M" \
    burst-time=10 \
    burst-threshold="8M/4M" \
    comment="Sales PC bandwidth limit"

# Limit entire subnet
add name="guest-vlan20" target="10.20.20.0/24" \
    max-limit="50M/20M" \
    comment="Guest VLAN total limit"

# === PCQ Queue Types (for Queue Tree) ===
/queue type
add name="pcq-download" kind=pcq pcq-classifier=dst-address pcq-rate=2M pcq-limit=100KiB
add name="pcq-upload" kind=pcq pcq-classifier=src-address pcq-rate=1M pcq-limit=100KiB

# === Mangle — mark connections for Queue Tree ===
/ip firewall mangle

# Mark LAN download
add chain=forward action=mark-connection \
    in-interface=ether1 \
    new-connection-mark="wan-download" \
    passthrough=yes \
    comment="Mark WAN download connections"

add chain=forward action=mark-packet \
    connection-mark="wan-download" \
    new-packet-mark="download" \
    passthrough=no \
    comment="Mark download packets"

# === Queue Tree ===
/queue tree

# Global WAN download queue
add name="download-total" parent=ether1 packet-mark=download \
    max-limit=100M queue=pcq-download comment="Total download PCQ"
