# Generated by MikroTik Config Tool
# Feature: vlan
# Generated: 2026-04-09T00:00:00Z

# === Bridge with VLAN filtering ===
/interface bridge add name="bridge-lan" vlan-filtering=yes protocol-mode=rstp comment="Main LAN bridge"

# === Bridge ports ===
/interface bridge port add bridge="bridge-lan" interface="ether2" pvid=1
/interface bridge port add bridge="bridge-lan" interface="ether3" pvid=10
/interface bridge port add bridge="bridge-lan" interface="ether4" pvid=20

# === Bridge VLAN table ===
/interface bridge vlan
add bridge="bridge-lan" tagged="bridge-lan" untagged="ether2" vlan-ids=1
add bridge="bridge-lan" tagged="bridge-lan,ether2" untagged="ether3" vlan-ids=10
add bridge="bridge-lan" tagged="bridge-lan,ether2" untagged="ether4" vlan-ids=20

# === VLAN interfaces ===
/interface vlan add name="vlan10" vlan-id=10 interface="bridge-lan" comment="Management VLAN"
/interface vlan add name="vlan20" vlan-id=20 interface="bridge-lan" comment="Guest VLAN"

# === IP Addresses on VLANs ===
/ip address add address="192.168.1.1/24" interface="bridge-lan" comment="Native VLAN gateway"
/ip address add address="10.10.10.1/24" interface="vlan10" comment="VLAN 10 gateway"
/ip address add address="10.20.20.1/24" interface="vlan20" comment="VLAN 20 gateway"
