# Generated by MikroTik Config Tool
# Feature: wireguard
# Generated: 2026-04-09T00:00:00Z

# === WireGuard Interface ===
/interface wireguard add name="wg0" listen-port=51820 mtu=1420 comment="VPN Tunnel"

# === WireGuard Peers ===
/interface wireguard peers add \
    interface="wg0" \
    public-key="BASE64_PUBLIC_KEY_HERE" \
    allowed-address="10.0.0.2/32,192.168.100.0/24" \
    endpoint-address="vpn.example.com" \
    endpoint-port=51820 \
    persistent-keepalive=25 \
    comment="Site A peer"

# === IP Address on WireGuard Interface ===
/ip address add address="10.0.0.1/24" interface="wg0" comment="WireGuard VPN subnet"

# === Route via WireGuard ===
/ip route add dst-address="192.168.100.0/24" gateway="wg0" comment="Route to Site A"
